### PR TITLE
Research capital designation

### PR DESCRIPTION
**Pull request by kirillgla**
I made sure it interacts correctly with distributism
image

### CODE REVIEW

**Comment by Rodahtnov** [comment]
Under consideration

**Comment by adriangaro** [comment]
We can probably merge, did want to make one myself either way.

**Comment by Rodahtnov** [comment]
Was already added on our own, will still credit for the initial idea

**Comment by Rodahtnov** [comment]
Was already added on our own, will still credit for the initial idea

**Pull request closed without merging**
